import "./global.css";
// import "bootstrap/dist/css/bootstrap.min.css";
// import BootstrapClient from "@/components/BootstrapClient";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function fun({ children }) {
  return (
    <div style={{
      background: "var(--mui-palette-background-paper)",
      color: "var(--mui-palette-text-primary)", height: '100vh'
    }}>
      {children}
    </div>
  );
}
